
spring:
  application:
    name: ${project.name}
#${project.name}

info:
  app:
    name: ${project.name}
    version: ${project.version}
    description: "roket"
#    java:
#      version: @java.version@

management:
  endpoints:
    web:
      exposure:
        include: "*"
#  management.endpoints.web.exposure.exclude=